macchina.selectByFilter = select m \
from Macchina m \
left join m.categoria c \
left join m.colore col \
left join m.marca mar \
left join m.alimentazione ali \
left join m.tipoVeicolo tv \
where (:id is null or m.id = :id) \
and (:targa is null or m.targa like concat(:targa, '%')) \
and (:numeroPorte is null or m.numeroPorte = :numeroPorte) \
and (:cc is null or m.cc = :cc) \
and (:categoria is null or c.id = :categoria) \
and (:colore is null or col.id = :colore) \
and (:marca is null or mar.id = :marca) \
and (:alimentazione is null or ali.id = :alimentazione) \
and (:tipoVeicolo is null or tv.id = :tipoVeicolo)

moto.selectByFilter = select m \
from Moto m \
left join m.categoria c \
left join m.colore col \
left join m.marca mar \
left join m.alimentazione ali \
left join m.tipoVeicolo tv \
where (:id is null or m.id = :id) \
and (:targa is null or m.targa like concat(:targa, '%')) \
and (:cc is null or m.cc = :cc) \
and (:categoria is null or c.id = :categoria) \
and (:colore is null or col.id = :colore) \
and (:marca is null or mar.id = :marca) \
and (:alimentazione is null or ali.id = :alimentazione) \
and (:tipoVeicolo is null or tv.id = :tipoVeicolo)

veicolo.selectByFilter = \
SELECT v \
FROM Veicolo v \
JOIN FETCH v.categoria c \
JOIN FETCH v.colore col \
JOIN FETCH v.marca mar \
JOIN FETCH v.alimentazione ali \
JOIN FETCH v.tipoVeicolo tv \
WHERE (:id IS NULL OR v.id = :id) \
  AND (:modello IS NULL OR LOWER(v.modello) LIKE LOWER(CONCAT(:modello, '%'))) \
  AND (:annoProduzione IS NULL OR v.annoProduzione = :annoProduzione) \
  AND (:numeroRuote IS NULL OR v.numeroRuote = :numeroRuote) \
  AND (:categoria IS NULL OR LOWER(c.categoria) = LOWER(:categoria)) \
  AND (:colore IS NULL OR LOWER(col.colore) = LOWER(:colore)) \
  AND (:marca IS NULL OR LOWER(mar.marca) = LOWER(:marca)) \
  AND (:alimentazione IS NULL OR LOWER(ali.alimentazione) = LOWER(:alimentazione)) \
  AND (:tipoVeicolo IS NULL OR LOWER(tv.veicolo) = LOWER(:tipoVeicolo)) \
  AND (:targa IS NULL OR (TYPE(v) = Macchina AND TREAT(v AS Macchina).targa LIKE CONCAT(:targa, '%'))) \
  AND (:numeroPorte IS NULL OR (TYPE(v) = Macchina AND TREAT(v AS Macchina).numeroPorte = :numeroPorte)) \
  AND (:cilindrataAuto IS NULL OR (TYPE(v) = Macchina AND TREAT(v AS Macchina).cc = :cilindrataAuto)) \
  AND (:targaMoto IS NULL OR (TYPE(v) = Moto AND TREAT(v AS Moto).targa LIKE CONCAT(:targaMoto, '%'))) \
  AND (:cilindrataMoto IS NULL OR (TYPE(v) = Moto AND TREAT(v AS Moto).cc = :cilindrataMoto)) \
  AND (:numeroMarce IS NULL OR (TYPE(v) = Bici AND TREAT(v AS Bici).numeroMarce = :numeroMarce)) \
  AND (:pieghevole IS NULL OR (TYPE(v) = Bici AND TREAT(v AS Bici).pieghevole = :pieghevole)) \
  AND (:sospensione IS NULL OR (TYPE(v) = Bici AND EXISTS (SELECT b FROM Bici b WHERE b.id = v.id AND LOWER(b.tipoSospensione.sospensione) = LOWER(:sospensione)))) \
  AND (:freno IS NULL OR (TYPE(v) = Bici AND EXISTS (SELECT b FROM Bici b WHERE b.id = v.id AND LOWER(b.tipoFreno.tipo) = LOWER(:freno))))


